### ISSUE TITLE
새로고침을 하지 않으면 기능이 작동하지 않습니다.

### ISSUE THREAD

**Issue by qsc7342** [VC-HTTP-Capstone/VC-HTTP-Capstone#1]
새로고침을 하지 않으면 기능이 작동하지 않습니다.
지갑 상태를 확인하거나, VC를 발급 혹은 제출 할 때 새로고침을 해야 기능이 작동하는데 해결이 필요합니다.

**Comment by jmk5315** [comment]
수정완료
